[jobs.run-serve]
command = ["cargo", "run", "--", "serve", "../output/directory.db", "../templates/", "../static/"]
watch = ["src/", "templates/"]
need_stdout = true
background = false
on_change_strategy = "kill_then_restart"
